; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "NamePicker"
#define MyAppVersion "v1.5.a"
#define MyAppPublisher "github@BaiZiDog"
#define MyAppURL "https://github.com/BaiZiDog/RandomNamePicker/"
#define MyAppExeName "helper.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
; ⚠ 本仓库约定：AppId 固定为下面这个值（以 v2.0 已发布的安装为准），后续每个版本都必须沿用。
;   AppId 不同会被 Inno 当成另一个程序，导致新版与旧版【并存安装】而不会覆盖升级；
;   历史版本（v1.5 / v1.5-fix）各自换过 GUID，正是并存问题的成因，不要照抄它们。
AppId={{5544B66A-CA07-4C55-9406-40B217CCA383}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; 用 {autopf} 而不是写死盘符：写死 D:\ 会让没有 D 盘的机器安装失败
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
LicenseFile=D:\PythonProject\RandomNamePicker\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\PythonProject\RandomNamePicker\release\1.5.a
OutputBaseFilename=NamePicker
SolidCompression=yes
WizardStyle=modern windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 取自本版暂存载荷 build\release-payload\v1.5.a（内容同 dist 产物，但 data\ 只含示例名单：
; 已排除真实名册 九班名册.txt，file.txt 指向 example.txt）。
Source: "D:\PythonProject\RandomNamePicker\build\release-payload\v1.5.a\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\PythonProject\RandomNamePicker\build\release-payload\v1.5.a\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

